### ISSUE TITLE
gtk-update-icon-cache: The generated cache was invalid.

### ISSUE THREAD

**Issue by awissu** [btd1337/elementary-full-icon-theme#11]
Icons with spaces:
find -name "* *"
```
./apps/48/gnome-control-center datetime.svg
./apps/48/gnome-control-center sound.svg
./apps/16/gnome-control-center datetime.svg
./apps/64/gnome-control-center datetime.svg
./apps/64/gnome-control-center sound.svg
./apps/24/gnome-control-center datetime.svg
./apps/24/gnome-control-center sound.svg
```
find -name "gnome-control-center *svg" -exec rm {} +
gtk-update-icon-cache --force /usr/share/icons/urutau-icons
`gtk-update-icon-cache: Cache file created successfully.`

**Comment by btd1337** [comment]
@awissu Thank you for your contribution! This functionality was implemented in commit 48c87d67e34cfaa7d0d29d345f10915ad4849f2c
