### ISSUE TITLE
Add icon: Signal Desktop (Signal Private Messenger)

### ISSUE THREAD

**Issue by pshemek** [btd1337/elementary-full-icon-theme#12]
Hello, nice to see this fresh and active project.
I wonder if you could add the icon for Signal Private Messenger.

**The app: (this is Electron app)**
https://signal.org/download/
**Icons folder:**
https://github.com/signalapp/Signal-Desktop/blob/development/images/

To run in tray:
`signal-desktop --start-in-tray`

**Comment by btd1337** [comment]
@macemmek Applications use a `.desktop` file to set the name of the icon they will point to.

This file is in the `/usr/share/applications/app_name.desktop` folder

Open this file in your text editor, find the **icon field**, and report here what icon name is used for this application.

**Comment by pshemek** [comment]
`Icon=signal-desktop`

**Comment by btd1337** [comment]
Solved in d3fcd882a699a41680e1752b93b370bb9d91c3db

**Comment by pshemek** [comment]
Thank you.
And what about the tray icon? It's blue; could we have it monochromatic?

**Comment by btd1337** [comment]
@macemmek Is you using elementary loki?
