### ISSUE TITLE
Needs guide/instructions on how to submit icons

### ISSUE THREAD

**Issue by AwesamLinux** [btd1337/elementary-full-icon-theme#16]
I think we need a simple guide/instructions on how to correctly submit icons. I am considering making a few icons, but I have never used GitHub before. So I'm not sure what the proper way to submit icons would be, and I'm probably not the only non-developer puzzled by this.

I'm not fluent with legal jargon in licensing documents either. But I assume there would be no issue with using official elementary OS icons as a base/template to build on?

**Comment by btd1337** [comment]
@AwesamLinux Look these links: 

https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

https://elementary.io/docs/human-interface-guidelines#iconography
