### ISSUE TITLE
Created a .deb files for you!

### ISSUE THREAD

**Issue by otavioschwanck** [btd1337/elementary-full-icon-theme#18]
https://www.dropbox.com/s/u0dsbs14gl3h11b/urutau-icons.deb?dl=0

Also added a terminal command, called set-urutau-icons that applies the icon theme.

Thanks for this great theme.

**Comment by btd1337** [comment]
Thanks for the contribution!

I'll add it to the project.

**Comment by btd1337** [comment]
Thanks for the contribution! 🎉

I'll add it to the project.

https://github.com/btd1337/urutau-icons/releases/tag/0.4
