### ISSUE TITLE
icon request: gcdemu

### ISSUE THREAD

**Issue by asmundur82** [btd1337/elementary-full-icon-theme#4]
Is it possible to revert gcdemu icon to a CD icon

**Comment by btd1337** [comment]
What is the name of the icon that this application points to?

Look in the file contained in the folder /usr/share/applications/

**Comment by asmundur82** [comment]
/usr/share/applications/gcdemu.desktop

**Comment by btd1337** [comment]
Open this file and locate the icon property. Post the result.

**Comment by asmundur82** [comment]
[Desktop Entry]
Version=1.0
Name=gCDEmu
Name[no]=gCDEmu
Name[ru]=gCDEmu
Name[sl]=gCDEmu
Name[sv]=gCDEmu
Comment=gCDEmu GUI
Comment[no]=gCDEmu GUI
Comment[ru]=Графический интерфейс gCDEmu
Comment[sl]=CDEmu grafični vmesnik
Comment[sv]=gCDEmu-GUI
Icon=gcdemu
Terminal=false
Type=Application
StartupNotify=false
Categories=GTK;System;
TryExec=gcdemu
Exec=gcdemu
X-GNOME-Autostart-Phase=Applications
X-GNOME-Autostart-Notify=false
X-GNOME-Autostart-enabled=false
# X-KDE-autostart-phase=2
# X-KDE-autostart-after=panel
# X-KDE-StartupNotify=false

**Comment by btd1337** [comment]
Is done in https://github.com/btd1337/elementary-full-icon-theme/commit/d128ed30c12cdd4c982bd8fc782eaf353dd2c146
