### ISSUE TITLE
icon request: makeMKV

### ISSUE THREAD

**Issue by asmundur82** [btd1337/elementary-full-icon-theme#5]
Hi is it possible to revert makemkv icon to a CD icon

**Comment by btd1337** [comment]
Can you make a pull request?

**Comment by asmundur82** [comment]
oh sorry i am new at this, i will make a pull request thank you

**Comment by asmundur82** [comment]
cant figure out the pull request section, i was wondering if it is possible to use a icon for makemkv that is already in the icon-theme perhaps dvd95.svg or dvdrip.svg, thanks in advance

**Comment by btd1337** [comment]
Support included in https://github.com/btd1337/elementary-full-icon-theme/commit/71174fe814b85331ed8d56c4f2f861785f0993fb

**Comment by asmundur82** [comment]
Hi icon is not showing

**Comment by asmundur82** [comment]
usr/share/applications/makemkv.desktop

**Comment by asmundur82** [comment]
[Desktop Entry]
Version=1.0
Name=MakeMKV
Comment=DVD and Blu-ray to MKV converter and network streamer
Exec=makemkv
Icon=makemkv
Terminal=false
Type=Application
Categories=AudioVideo;Qt;

**Comment by btd1337** [comment]
The icon has been set. Be sure to update your icon pack.

Enter in icon pack folder (elementary-full-icon-theme) and update:

`git pull`

If you made any previous changes it's necessary make merge of the changes.

`git merge`
`git pull`

![captura de tela de 2017-06-25 13-05-59](https://user-images.githubusercontent.com/11943860/27517714-2af29996-59a7-11e7-8af5-1323d20d265e.png)
![captura de tela de 2017-06-25 13-06-19](https://user-images.githubusercontent.com/11943860/27517713-2ad71eb4-59a7-11e7-9246-65b6eaa02ad1.png)

**Comment by asmundur82** [comment]
Hi, i have updated but there is no icon showing for makemkv and gcdemu

**Comment by btd1337** [comment]
Thanks for your report. I fixed this in https://github.com/btd1337/elementary-full-icon-theme/commit/7b390683c83f8451469c035cbe1ac9351c610fd6 . Try again.

**Comment by asmundur82** [comment]
thanks that worked
